services:
  postgres:
    image: postgres:16
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    restart: unless-stopped
    networks:
      - open-doc-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web-server:
    build: ../web-server/
    environment:
      - API_PORT=${API_PORT}
      - DB_HOST=postgres
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER_NAME=${DB_USER_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
    restart: unless-stopped
    networks:
      - open-doc-network
    depends_on:
      - postgres

  webrtc-signaling:
    build: ../webrtc-signaling
    environment:
      - SIGNALING_PORT=${SIGNALING_PORT}
    networks:
      - open-doc-network

  web-client:
    build:
      context: ../web-client/
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
        VITE_SIGNALING_SERVER_HOST: ${VITE_SIGNALING_SERVER_HOST}
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    networks:
      - open-doc-network
    volumes:
      - ssl-cert:/etc/letsencrypt:ro
      - webroot:/var/www/certbot:ro
    # depends_on:
    #   - certbot

  # certbot:
  #   build: ./ssl-certificate/
  #   environment:
  #     - APP_DOMAIN=${APP_DOMAIN}
  #     - SSL_EMAIL=${SSL_EMAIL}
  #   volumes:
  #     - ssl-cert:/etc/letsencrypt
  #     - webroot:/var/www/certbot
  #   network_mode: host

  # certbot-renew:
  #   build: ./ssl-certificate-renew/
  #   restart: unless-stopped
  #   volumes:
  #     - ssl-cert:/etc/letsencrypt
  #     - webroot:/var/www/certbot
  #   depends_on:
  #     - web-server


volumes:
  postgres_data:
  ssl-cert:
  webroot:

networks:
  open-doc-network:
    driver: bridge