server {
    listen 80;
    server_name open-doc.cloud;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$server_name$request_uri;
    }
}

server {
    listen 443 ssl;

    root /usr/share/nginx/html;
    index index.html;

    ssl_certificate     /etc/letsencrypt/live/open-doc.cloud/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/open-doc.cloud/privkey.pem;

    # API proxy
    location /api/ {
        proxy_pass http://web-server:8080/api/;
        proxy_set_header Host $host;
    }

    # Frontend SPA
    location / {
        try_files $uri $uri/ /index.html;
    }
}