// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8080' | (string & {});
};

export type SignUpRequestDto = {
    name: string;
    password: string;
    email: string;
};

export type SignInRequestDto = {
    password: string;
    email: string;
};

export type CreateArticleRequestDto = {
    title?: string;
    content?: string;
};

export type ArticleResponseDto = {
    id?: string;
    title?: string;
    content?: string;
    createdAt?: string;
};

export type SignUpData = {
    body: SignUpRequestDto;
    path?: never;
    query?: never;
    url: '/api/v1/auth/sign-up';
};

export type SignUpResponses = {
    /**
     * OK
     */
    200: string;
};

export type SignUpResponse = SignUpResponses[keyof SignUpResponses];

export type SignInData = {
    body: SignInRequestDto;
    path?: never;
    query?: never;
    url: '/api/v1/auth/sign-in';
};

export type SignInResponses = {
    /**
     * OK
     */
    200: string;
};

export type SignInResponse = SignInResponses[keyof SignInResponses];

export type GetArticlesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/articles';
};

export type GetArticlesResponses = {
    /**
     * OK
     */
    200: Array<ArticleResponseDto>;
};

export type GetArticlesResponse = GetArticlesResponses[keyof GetArticlesResponses];

export type CreateArticleData = {
    body: CreateArticleRequestDto;
    path?: never;
    query?: never;
    url: '/api/v1/articles';
};

export type CreateArticleResponses = {
    /**
     * OK
     */
    200: ArticleResponseDto;
};

export type CreateArticleResponse = CreateArticleResponses[keyof CreateArticleResponses];
