// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8080' | (string & {});
};

export type CreateArticleRequestDto = {
    title?: string;
    content?: string;
};

export type ArticleResponseDto = {
    id?: string;
    title?: string;
    content?: string;
    createdAt?: string;
};

export type GetArticlesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/articles';
};

export type GetArticlesResponses = {
    /**
     * OK
     */
    200: Array<ArticleResponseDto>;
};

export type GetArticlesResponse = GetArticlesResponses[keyof GetArticlesResponses];

export type CreateArticleData = {
    body: CreateArticleRequestDto;
    path?: never;
    query?: never;
    url: '/api/v1/articles';
};

export type CreateArticleResponses = {
    /**
     * OK
     */
    200: ArticleResponseDto;
};

export type CreateArticleResponse = CreateArticleResponses[keyof CreateArticleResponses];
