on:
  pull_request:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'oracle'
          java-version: '25'

      - name: Test web-server
        run: |
          cd web-server
          ./mvnw test
      - name: Second steps
        run: |
          echo "hit"