name: PR Checks
on:
  pull_request:
    branches: [master]

jobs:
  ci-web-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Run backend tests
        uses: ./.github/actions/web-server-ci

  ci-web-client:
    runs-on: ubuntu-latest
    steps:
      - name: Run frontend tests
        uses: ./.github/actions/web-client-ci